python3 reuse_data_collector.py py cs_repos/catkin
python3 reuse_data_collector.py py cs_repos/bbqsql
python3 reuse_data_collector.py py cs_repos/plone.app.layout
python3 reuse_data_collector.py py cs_repos/rainbow
python3 reuse_data_collector.py py cs_repos/ColdFusion
python3 reuse_data_collector.py py cs_repos/mcstatus
python3 reuse_data_collector.py py cs_repos/amitools
python3 reuse_data_collector.py py cs_repos/salt-contrib
python3 reuse_data_collector.py py cs_repos/plone.app.theming
python3 reuse_data_collector.py py cs_repos/oauthlib
python3 reuse_data_collector.py py cs_repos/pure-python-otr
python3 reuse_data_collector.py py cs_repos/plone.app.discussion
python3 reuse_data_collector.py py cs_repos/fast-export
python3 reuse_data_collector.py py cs_repos/h
python3 reuse_data_collector.py py cs_repos/xunlei-lixian
python3 reuse_data_collector.py py cs_repos/cms
python3 reuse_data_collector.py py cs_repos/pybossa
python3 reuse_data_collector.py py cs_repos/Products.TinyMCE
python3 reuse_data_collector.py py cs_repos/Transliteration
python3 reuse_data_collector.py py cs_repos/transifex-client
python3 reuse_data_collector.py py cs_repos/git-bz-moz
python3 reuse_data_collector.py py cs_repos/plone.app.workflowmanager
python3 reuse_data_collector.py py cs_repos/CaseConversion
python3 reuse_data_collector.py py cs_repos/django-easy-maps
python3 reuse_data_collector.py py cs_repos/ViTables
python3 reuse_data_collector.py py cs_repos/advene
python3 reuse_data_collector.py py cs_repos/apt-offline
python3 reuse_data_collector.py py cs_repos/Arelle
python3 reuse_data_collector.py py cs_repos/Arkestra
python3 reuse_data_collector.py py cs_repos/autopep8
python3 reuse_data_collector.py py cs_repos/awesim
python3 reuse_data_collector.py py cs_repos/bartendro
python3 reuse_data_collector.py py cs_repos/bcfg2
python3 reuse_data_collector.py py cs_repos/biostar-central
python3 reuse_data_collector.py py cs_repos/bitbake
python3 reuse_data_collector.py py cs_repos/bitHopper
python3 reuse_data_collector.py py cs_repos/Bookie
python3 reuse_data_collector.py py cs_repos/ccm
python3 reuse_data_collector.py py cs_repos/cecog
python3 reuse_data_collector.py py cs_repos/census
python3 reuse_data_collector.py py cs_repos/clcache
python3 reuse_data_collector.py py cs_repos/collective.developermanual
python3 reuse_data_collector.py py cs_repos/cuisine
python3 reuse_data_collector.py py cs_repos/cuppa
python3 reuse_data_collector.py py cs_repos/d3py
python3 reuse_data_collector.py py cs_repos/django-audit-log
python3 reuse_data_collector.py py cs_repos/django-boundaryservice
python3 reuse_data_collector.py py cs_repos/django-cms-search
python3 reuse_data_collector.py py cs_repos/django-cumulus
python3 reuse_data_collector.py py cs_repos/django-ratelimit
python3 reuse_data_collector.py py cs_repos/django-security
python3 reuse_data_collector.py py cs_repos/django-states2
python3 reuse_data_collector.py py cs_repos/djangopeople
python3 reuse_data_collector.py py cs_repos/dnsrecon
python3 reuse_data_collector.py py cs_repos/docs
python3 reuse_data_collector.py py cs_repos/docs
python3 reuse_data_collector.py py cs_repos/documentation
python3 reuse_data_collector.py py cs_repos/econsensus
python3 reuse_data_collector.py py cs_repos/emokit
python3 reuse_data_collector.py py cs_repos/ensime-sublime
python3 reuse_data_collector.py py cs_repos/eulxml
python3 reuse_data_collector.py py cs_repos/exitwp
python3 reuse_data_collector.py py cs_repos/fabulaws
python3 reuse_data_collector.py py cs_repos/facebook-sdk
python3 reuse_data_collector.py py cs_repos/factory_boy
python3 reuse_data_collector.py py cs_repos/flask-mongoalchemy
python3 reuse_data_collector.py py cs_repos/Flexget
python3 reuse_data_collector.py py cs_repos/frappe
python3 reuse_data_collector.py py cs_repos/froide
python3 reuse_data_collector.py py cs_repos/Frozen-Flask
python3 reuse_data_collector.py py cs_repos/fuzzywuzzy
python3 reuse_data_collector.py py cs_repos/gargoyle
python3 reuse_data_collector.py py cs_repos/geany-themes
python3 reuse_data_collector.py py cs_repos/ginkgo
python3 reuse_data_collector.py py cs_repos/hamper
python3 reuse_data_collector.py py cs_repos/headphones
python3 reuse_data_collector.py py cs_repos/horton
python3 reuse_data_collector.py py cs_repos/httpbin
python3 reuse_data_collector.py py cs_repos/HunchWorks
python3 reuse_data_collector.py py cs_repos/icalendar
python3 reuse_data_collector.py py cs_repos/ijson
python3 reuse_data_collector.py py cs_repos/Intranet
python3 reuse_data_collector.py py cs_repos/klaus
python3 reuse_data_collector.py py cs_repos/koalixcrm
python3 reuse_data_collector.py py cs_repos/ktbs
python3 reuse_data_collector.py py cs_repos/LaTeXTools
python3 reuse_data_collector.py py cs_repos/lazyflow
python3 reuse_data_collector.py py cs_repos/lettuce_webdriver
python3 reuse_data_collector.py py cs_repos/libthumbor
python3 reuse_data_collector.py py cs_repos/livestreamer
python3 reuse_data_collector.py py cs_repos/markdown-redcarpet.tmbundle
python3 reuse_data_collector.py py cs_repos/Memacs
python3 reuse_data_collector.py py cs_repos/minimongo
python3 reuse_data_collector.py py cs_repos/mittun
python3 reuse_data_collector.py py cs_repos/monitoring
python3 reuse_data_collector.py py cs_repos/mozillians
python3 reuse_data_collector.py py cs_repos/MozSecWorld
python3 reuse_data_collector.py py cs_repos/mpDris2
python3 reuse_data_collector.py py cs_repos/Multicorn
python3 reuse_data_collector.py py cs_repos/ncclient
python3 reuse_data_collector.py py cs_repos/nodeenv
python3 reuse_data_collector.py py cs_repos/otm-legacy
python3 reuse_data_collector.py py cs_repos/pattern
python3 reuse_data_collector.py py cs_repos/pelita
python3 reuse_data_collector.py py cs_repos/percol
python3 reuse_data_collector.py py cs_repos/podio-py
python3 reuse_data_collector.py py cs_repos/Printrun
python3 reuse_data_collector.py py cs_repos/proteus
python3 reuse_data_collector.py py cs_repos/psycopg2-ctypes
python3 reuse_data_collector.py py cs_repos/pyBurlyBot
python3 reuse_data_collector.py py cs_repos/pydpiper
python3 reuse_data_collector.py py cs_repos/pydub
python3 reuse_data_collector.py py cs_repos/PyHamcrest
python3 reuse_data_collector.py py cs_repos/pyjwt
python3 reuse_data_collector.py py cs_repos/pyramid_debugtoolbar
python3 reuse_data_collector.py py cs_repos/Pyrseas
python3 reuse_data_collector.py py cs_repos/PySide
python3 reuse_data_collector.py py cs_repos/pystun
python3 reuse_data_collector.py py cs_repos/PySurfer
python3 reuse_data_collector.py py cs_repos/pyswf
python3 reuse_data_collector.py py cs_repos/python-clouddns
python3 reuse_data_collector.py py cs_repos/python-ebay
python3 reuse_data_collector.py py cs_repos/python-haystack
python3 reuse_data_collector.py py cs_repos/python-hpilo
python3 reuse_data_collector.py py cs_repos/python-netfilterqueue
python3 reuse_data_collector.py py cs_repos/python-snappy
python3 reuse_data_collector.py py cs_repos/python4astronomers
python3 reuse_data_collector.py py cs_repos/pyxmpp2
python3 reuse_data_collector.py py cs_repos/s3cmd
python3 reuse_data_collector.py py cs_repos/scielo-manager
python3 reuse_data_collector.py py cs_repos/scikit-image
python3 reuse_data_collector.py py cs_repos/snimpy
python3 reuse_data_collector.py py cs_repos/sonospy
python3 reuse_data_collector.py py cs_repos/streaming-system
python3 reuse_data_collector.py py cs_repos/SublimeCodeIntel
python3 reuse_data_collector.py py cs_repos/svtplay-dl
python3 reuse_data_collector.py py cs_repos/tablib
python3 reuse_data_collector.py py cs_repos/tcollector
python3 reuse_data_collector.py py cs_repos/tldextract
python3 reuse_data_collector.py py cs_repos/ToMaTo
python3 reuse_data_collector.py py cs_repos/unstdlib.py
python3 reuse_data_collector.py py cs_repos/youtify
python3 reuse_data_collector.py py cs_repos/zato
python3 reuse_data_collector.py py cs_repos/conky_colors
python3 reuse_data_collector.py py cs_repos/xapi-storage
python3 reuse_data_collector.py py cs_repos/securedrop
python3 reuse_data_collector.py py cs_repos/makahiki
python3 reuse_data_collector.py py cs_repos/pymeshio
python3 reuse_data_collector.py py cs_repos/QuantitativeReporting
python3 reuse_data_collector.py py cs_repos/OWSLib
python3 reuse_data_collector.py py cs_repos/sh
python3 reuse_data_collector.py py cs_repos/SublimeGDB
python3 reuse_data_collector.py py cs_repos/kartograph.py
python3 reuse_data_collector.py py cs_repos/boxoffice
python3 reuse_data_collector.py py cs_repos/django-tracking2
python3 reuse_data_collector.py py cs_repos/django-oauth2-provider
python3 reuse_data_collector.py py cs_repos/owtf
python3 reuse_data_collector.py py cs_repos/symfony-cmf-docs
python3 reuse_data_collector.py py cs_repos/scikit-rf
python3 reuse_data_collector.py py cs_repos/gmusicapi
python3 reuse_data_collector.py py cs_repos/tlslite
python3 reuse_data_collector.py py cs_repos/pycparserext
python3 reuse_data_collector.py py cs_repos/Minecraft
python3 reuse_data_collector.py py cs_repos/orgmode
python3 reuse_data_collector.py py cs_repos/q
python3 reuse_data_collector.py py cs_repos/collective.plonetruegallery
python3 reuse_data_collector.py py cs_repos/eea.facetednavigation
python3 reuse_data_collector.py py cs_repos/Coherence
python3 reuse_data_collector.py py cs_repos/pydocstyle
python3 reuse_data_collector.py py cs_repos/pybbm
python3 reuse_data_collector.py py cs_repos/jpylyzer
python3 reuse_data_collector.py py cs_repos/prestapyt
python3 reuse_data_collector.py py cs_repos/fedmsg
python3 reuse_data_collector.py py cs_repos/confuse
python3 reuse_data_collector.py py cs_repos/AndroidViewClient
python3 reuse_data_collector.py py cs_repos/antfs-cli
python3 reuse_data_collector.py py cs_repos/django-cbv-inspector
python3 reuse_data_collector.py py cs_repos/klein
python3 reuse_data_collector.py py cs_repos/sage-patchbot
python3 reuse_data_collector.py py cs_repos/gae-boilerplate
python3 reuse_data_collector.py py cs_repos/sublemacspro
python3 reuse_data_collector.py py cs_repos/scrumbugz
python3 reuse_data_collector.py py cs_repos/softlayer-object-storage-python
python3 reuse_data_collector.py py cs_repos/amigaos-cross-toolchain
python3 reuse_data_collector.py py cs_repos/django-daguerre
python3 reuse_data_collector.py py cs_repos/relman-auto-nag
python3 reuse_data_collector.py py cs_repos/mikidown
python3 reuse_data_collector.py py cs_repos/prymatex
python3 reuse_data_collector.py py cs_repos/CoilSnake
python3 reuse_data_collector.py py cs_repos/PySocks
