python3 reuse_data_collector.py py cs_repos/EvaP
python3 reuse_data_collector.py py cs_repos/dojango
python3 reuse_data_collector.py py cs_repos/plone.app.portlets
python3 reuse_data_collector.py py cs_repos/Glyphs-Scripts
python3 reuse_data_collector.py py cs_repos/diazo
python3 reuse_data_collector.py py cs_repos/CloudBotLegacy
python3 reuse_data_collector.py py cs_repos/citeproc-py
python3 reuse_data_collector.py py cs_repos/django-simple-captcha
python3 reuse_data_collector.py py cs_repos/Products.CMFPlone
python3 reuse_data_collector.py py cs_repos/IbPy
python3 reuse_data_collector.py py cs_repos/customizer
python3 reuse_data_collector.py py cs_repos/PyMultiNest
python3 reuse_data_collector.py py cs_repos/fortran90.org
python3 reuse_data_collector.py py cs_repos/buildout.coredev
python3 reuse_data_collector.py py cs_repos/plone.app.contenttypes
python3 reuse_data_collector.py py cs_repos/django-chartit
python3 reuse_data_collector.py py cs_repos/sae-python-dev-guide
python3 reuse_data_collector.py py cs_repos/django-fluent-contents
python3 reuse_data_collector.py py cs_repos/django-dynamic-fixture
python3 reuse_data_collector.py py cs_repos/django-timepiece
